### ISSUE TITLE
problème pour build le site

### ISSUE THREAD

**Issue by elisefilotas** [sci1031/sci1031#30]
Allo Kevin,
J'ai encore un problème qui arrive à l'étape de "Install Dependencies".
Hier j'ai pushé des changements et ça a fonctionné sans problème. 
La seule chose qui a vraiment changé dans mon code depuis hier, c'est l'usage de la librairie leafsync.
Tu crois que ça peut être lié?

Merci!
Elise

**Comment by KevCaz** [comment]
Semble que ce soit lié à l'update de cpp11; voir: 
- https://github.com/r-lib/cpp11/issues/88
- https://stackoverflow.com/questions/63348263/cant-install-tidyverse-on-latest-version-of-linux-mint

Le mieux c'est d'attendre!

**Comment by KevCaz** [comment]
Et il y a déjà un patch sur la version dev.... pour le cran ça peut prendre qq jours, mais on a **rien** a faire pour le moment!

**Comment by elisefilotas** [comment]
Dac, merci d'avoir investiguer!

**Comment by SteveViss** [comment]
Le message d'erreur à changer: 

```
Error: path for html_dependency not found: 
 - attr(*, "class")= chr "html_dependency"
```

Cela semble relié à la cache de knitr: https://github.com/rstudio/bookdown/issues/15

**Comment by SteveViss** [comment]
Voir le log du build sur la branche dev-mod8

**Comment by KevCaz** [comment]
@SteveViss ce problème est dû à mapview, voir https://github.com/r-spatial/mapview/issues/312. 
En utilisant la version de dev comme indiquer dans le lien ci-dessus, le problème est résolu. Les checks ne passent pas à cause du déploiement, on peut donc merger quand vous voulez.

**Comment by SteveViss** [comment]
Awesome !

**Comment by SteveViss** [comment]
Il y a un autre problème avec la taille d'un module. Je regarde ca ce soir.

**Comment by SteveViss** [comment]
Ref: `remote: error: File leçon-5.html is 112.22 MB; this exceeds GitHub's file size limit of 100.00 MB`

**Comment by SteveViss** [comment]
This issue has been resolved. Any new commits will trigger a new build (handle by github actions).
