### ISSUE TITLE
Uniformiser le style

### ISSUE THREAD

**Issue by KevCaz** [sci1031/sci1031#33]
Ce serait bien d'avoir une page de wiki (ou cette page d'issue) pour avoir des indications sur le style. 
Par exemple quand on présente une fonction, e.g.  st_crs, je préfère utiliser le format code avec une parenthèse, i.e. 
```md
`st_crs()`
```
et pour les packages, variables, etc. le même format "code" sans parenthèse. 

Aussi, pour les nombres avec unités, avec HTML le mieux c'est `&nbsp;`, e.g. `70&nbsp;kms`

**Comment by SteveViss** [comment]
Done: https://github.com/sci1031/sci1031/wiki/Guide-des-styles. À updater en continu.
