### ISSUE TITLE
Probleme avec le dernier merge

### ISSUE THREAD

**Issue by KevCaz** [sci1031/sci1031#37]
Salut @elisefilotas, dans ton dernier merge, tu as enlevé tous nos derniers changements (de ce week-end) notamment ceux qui résolvent le temps de build (#30). Je dois donc enlever cette dernière commit, je vais me débrouiller pour remettre tes changements sur le texte du module 7.

**Comment by KevCaz** [comment]
Les lignes suivantes ne sont plus valides, les data ne sont pas là.
https://github.com/sci1031/sci1031/blob/2d48b6c4624f25cc748fe8ed8f3cd1bc48e613c4/Module7/index.Rmd#L409-L412

**Comment by elisefilotas** [comment]
Oh fudge. Je suis vraiment désolée.
J'ai commencé à travailler sur le module 7 jeudi dernier, et j'ai continué lundi sans réaliser que vous aviez travaillé dessus.
(je pensais sincèrement que vous alliez travailler sur le module 8)
Est-ce beaucoup de travail de merger mes changements avec les vôtres?
J'imagine que ça règlera le problème de données qui ont changé de nom?
Je m'excuse!

**Comment by KevCaz** [comment]
Y'a 0 pb la, on a oublié de communiquer. 
Jai fait les changements, je suis pret a merger la bonne version si tu es ok. Je vais devoir forcer le push, c'est tout.

**Comment by elisefilotas** [comment]
Dac!

**Comment by KevCaz** [comment]
J'ai remis le module 7 comme il faut (il me semble), mais maintenant on a des pb avec mapview (qui commencent aux modules 4). 
Je n'arrive pas è reproduire ces pb en local, j'ai essayé 2-3 trucs, en vain.

**Comment by elisefilotas** [comment]
Et il n'y avait pas ces problèmes avant que je joue avec le module 7?
Donc, ça serait mes edits qui ont "fucké" l'affaire?
Comment je trouve les lignes qui sont problématiques?

**Comment by KevCaz** [comment]
Je ne pense pas que ce soit tes lignes qui soient le problème, tu as juste changé le module 7 et on a des problèmes des le module 4. Y'a qqchose qui va mal avec mapview.

**Comment by elisefilotas** [comment]
Ok.
Mais bizarre que le module 4 et 7 (avant que je fasse les modifs) fonctionnaient avant.

**Comment by KevCaz** [comment]
Je suis capable de reproduire le problème avec la dernière version de mapview (en devel). Pas sur qu'on puisse faire de quoi, peut être ne pas prendre la dernière commit ou attendre la prochaine... une fois que se sera réglé, avec ce qu'on a mis en place ce week-end, les changements de versions de package ne devrait plus poser de problèmes.

**Comment by elisefilotas** [comment]
Ah! Donc c'est un problème avec la dernière version de mapview.

**Comment by KevCaz** [comment]
Pb réglé! https://sci1031.github.io/sci1031/

**Comment by KevCaz** [comment]
En fait on lui demandait d'être sur la HEAD du repo GH mais la dernière commit pose problème!

**Comment by KevCaz** [comment]
Faudra que tu inspectes un peu le module 7, y'a un passage ou j'étais pas bien sur de ce qui étais mieux.

https://github.com/sci1031/sci1031/blob/17d4978b9c5a0d144581db1c372cea07a2613ef3/Module7/index.Rmd#L336-L424

**Comment by elisefilotas** [comment]
Nice, trop cool!
D'accord, je checke ce passage.
