### ISSUE TITLE
Présence de rgdal et sp

### ISSUE THREAD

**Issue by KevCaz** [sci1031/sci1031#38]
Du coup j'ai commencé à regarder le contenu et je me demande pourquoi om a `rgdal`.

```md
Pour lire des données vectorielles contenues dans un fichier *shapefile*, nous allons utiliser la librairie `sf`. 
Notez que la librairie `rgdal` se charge automatiquement lorsque `sf` se charge.
```

Ça c'était vrai avec `sp` (qui était un package de classes en fait et qui avait besoin de rgdal pour faire les conversions) mais plus avec `sf`. En fait je pense qu'on peut enlever `sp` et  `rgdal` de tout le cours.

**Comment by SteveViss** [comment]
À valider qu'il n'y aura pas de trace de ces packages dans le cours lors de la validation. Je garde l'issue ouverte pour que ca reste flagger.
