### ISSUE TITLE
module cartographie: tmap vs ggplot2

### ISSUE THREAD

**Issue by elisefilotas** [sci1031/sci1031#43]
Bonjour @SteveViss et @KevCaz ,

Je commence le module 6 qui portera sur la cartographie. En gros:
- Considérations pour créer des bonnes cartes
- Fonctions et options R pour faire différents types de carte.

Initialement, je pensais mettre l'accent sur l'utilisation de ggplot mais je commence à pencher pour tmap.
J'étais curieuse de connaître votre opinion.
Je pense que l'apprentissage de ggplot est plus intéressant sur le long-terme car les étudiants pourront utiliser la même syntaxe quand ils seront amenés à utiliser d'autres données pas nécessairement spatiales.
En même temps, Lovelace et al. dans leur livre Geocomputation with R (que je trouve vraiment bon) se concentre sur tmap, avec un petit survol de ggplot: https://bookdown.org/robinlovelace/geocompr/adv-map.html.
Je pourrais faire pareille. J'ai l'impression que tmap est plus simple à enseigner et utiliser.

tmap permet aussi de créer des cartes dynamiques ce qui pourraient être utiliser au module 9?
https://bookdown.org/robinlovelace/geocompr/adv-map.html#animated-maps

En tout cas, dites-moi si vous pensez qu'il y a des problèmes connus avec tmap et que je fais un 'disservice' aux étudiants en me concentrant sur ce package.

Ah oui, et la partie exercice porterait sur leaflet.

À plus,
Elise

**Comment by KevCaz** [comment]
J'ai que des bons retours sur tmap! Je ne pense pas que ce soit un problème. Honnêtement, le plus grands services à rendre aux étudiants c'est de les rendre capables de passer d'un package à l'autre sans qu'ils soient complètement perdus juste parce qu'ils ont changé de package!

**Comment by elisefilotas** [comment]
OK, super, merci pour le feedback!
