### ISSUE TITLE
mapview et raster

### ISSUE THREAD

**Issue by KevCaz** [sci1031/sci1031#45]
Avec mapview après l'affichage de 1 raster le second ne marche plus.

**Comment by KevCaz** [comment]
See https://github.com/r-spatial/mapview/issues/360

**Comment by elisefilotas** [comment]
Toujours pas de réponse hein?

**Comment by KevCaz** [comment]
Non! Il a très certainement vu problème, mais il n'a pas commenté. Une solution pourrait faire une simple fonction leaflet pour les rasters pour notre usage.

**Comment by elisefilotas** [comment]
Ok. Ce n'est pas mon option favorite, mais je pense qu'on a pas le choix.
Je n'ai pas encore terminé le module 6 qui utilise juste tmap. 
Lorsque terminé, si toujours pas de réponse du gars de mapview, on contourne le problème avec leaflet.

**Comment by KevCaz** [comment]
Ça me semble une bonne idée!

**Comment by KevCaz** [comment]
J'ai trouvé le problème. ==> https://github.com/r-spatial/mapview/issues/360. Le plus simple c'est de mettre `homebutton = FALSE` pour le moment.

**Comment by KevCaz** [comment]
Le problème a été réglé depuis, voir https://github.com/r-spatial/leafem/commit/e4fba9e787a5095d60735ab937d40a921f35e4ac.
