### ISSUE TITLE
retirer fichier trop gros

### ISSUE THREAD

**Issue by elisefilotas** [sci1031/sci1031#49]
Allo @SteveViss,
peux-tu me donner la commande pour retirer le raster trop gros (>150Mb) que j'ai pushé dimanche dernier?
Il semble que je ne puisse plus rien pushé à cause que ce fichier traine dans les limbes de git.
Merci!
Elise

**Comment by KevCaz** [comment]
Du coup @elisefilotas , celui la on peut le clore?
