### ISSUE TITLE
pull

### ISSUE THREAD

**Issue by elisefilotas** [sci1031/sci1031#51]
Allo @KevCaz,

Je viens de puller la master localement, et je m'apprête à la merger à ma branche, et j'ai un petit stress pcq je ne comprends pas le message de git:

![image](https://user-images.githubusercontent.com/41080954/111007268-70f0ef00-835c-11eb-9046-06c11dbf5bfc.png)

Déjà. j'avais répondu y à la question plus haut, sans trop être certaine.

Tu me diras si je peux répondre oui ici.

Merci!
Elise

**Comment by KevCaz** [comment]
Nope. Tu dois d'abord puller ta branche. Je m'étais occupé de merger ta branche avec la master pour que tu n'es plus qu'à puller ta branche (seulement ta branche). J'ai surement pas été claire quand j'ai dit "t'auras plus qu'à puller".

**Comment by elisefilotas** [comment]
zut, je pense que j'ai raté.
Là il ne veut plus que je pull...

![image](https://user-images.githubusercontent.com/41080954/111010051-5cfcbb80-8363-11eb-920f-cce185be4d75.png)

Je dois aller faire le souper (!!)
Au pire on s'en reparle dimanche.

**Comment by KevCaz** [comment]
essayes 

```
git merge --abort
git pull 
```

**Comment by elisefilotas** [comment]
Allo @KevCaz,
J'ai un issue similaire à ce qu'on discutait il y a quelques temps.

Je viens de pull localement la master. 
Mon but est de pouvoir réviser le Module8.

Le pull fonctionne, mais là je ne suis pas capable de retourner sur ma branche.
J'obtiens ceci:
![image](https://user-images.githubusercontent.com/41080954/114580852-37f2b580-9c4d-11eb-82a1-c9caa618dd82.png)

Le problème semble être lié à des permissions. 
Devrais-je répondre Oui à la question au lieu de Non?

Elise

**Comment by KevCaz** [comment]
On en parle de vive voix aujourd,hui?

**Comment by elisefilotas** [comment]
Oui! J'ai un meeting à 14h, mais je devrais être libre vers 14h30.
Ou n'importe quand après.

**Comment by KevCaz** [comment]
ok, la j'ai un meeting qui va s'étendre sur pas mal tout le pm.

**Comment by elisefilotas** [comment]
ah zut. J'ai fini mon meeting. donc si jamais tu deviens libre fais-moi signe.

**Comment by KevCaz** [comment]
Du coup plutot demain pour moi!

**Comment by elisefilotas** [comment]
J'ai ce meeting demain en am ...
Libre en pm par contre. Si jamais.

**Comment by KevCaz** [comment]
possible, après 2pm par contre!

**Comment by elisefilotas** [comment]
Ça me va, merci!

**Comment by elisefilotas** [comment]
Tu me fais signe quand tu peux?

**Comment by KevCaz** [comment]
Dans 5 min sur google team?

**Comment by elisefilotas** [comment]
parfait

**Comment by KevCaz** [comment]
On a reglé celui la il y a un certain temps.
