### ISSUE TITLE
preview_chapter

### ISSUE THREAD

**Issue by elisefilotas** [sci1031/sci1031#55]
Salut @KevCaz,

J'aimerais vraiment pouvoir utiliser la fonction preview_chapter pour ne pas avoir à recompiler tout le livre juste pour checker l'apparence du module 6.

Il n'y a pas beaucoup d'info ici: https://bookdown.org/yihui/bookdown/preview-a-chapter.html

Et en lisant ceci: https://stackoverflow.com/questions/63521386/bookdown-preview-chapter
Je déduis que je pourrais simplement faire:
bookdown::preview_chapter('Module6/index.Rmd', 'bookdown::gitbook')

Mais ça ne fonctionne pas.

Idées?

Merci!
Elise

**Comment by KevCaz** [comment]
Je regarde ça dans vraiment pas long.

**Comment by KevCaz** [comment]
Perso ça marche, est-ce que tu as une erreur de retournée?

**Comment by KevCaz** [comment]
@elisefilotas, voila ce que j'ai 

```R
 bookdown::preview_chapter('Module6/index.Rmd', 'bookdown::g
   itbook') 
[...] 
Output created: _book/index.html
[1] "/home/kevcaz/Projects/books/sci1031/_book/index.html"
```

**Comment by KevCaz** [comment]
Si y'a de quoi on peut faire un meeting.

**Comment by KevCaz** [comment]
@elisefilotas, Après recherche, il y a 1 problème avec la version stable https://github.com/rstudio/bookdown/issues/1003 tu as besoin de la version de dev

**Comment by elisefilotas** [comment]
Je n'ai pas de messages d'erreur, j'ai le même output que celui que tu obtiens. Mais seul le main index.html apparaît et pas celui du module 6.

cela ton dernier commentaire, je comprends que je dois installer la version en développement de bookdown? Comment je fais ça? simplement un update du package?

**Comment by KevCaz** [comment]
Comme pour Mapview,

```R
install.packages("remotes")
remotes::install_github("rstudio/bookdown")
```

**Comment by KevCaz** [comment]
@elisefilotas fais moi signe si tu as des problémes!

**Comment by elisefilotas** [comment]
ouin, j'ai quelques problèmes. fais-moi signe si on peut chater

**Comment by KevCaz** [comment]
je suis sur google meet
