### ISSUE TITLE
get_evel_raster()

### ISSUE THREAD

**Issue by elisefilotas** [sci1031/sci1031#57]
Allo @KevCaz,

J'ai un problème avec la fonction get_evel_raster() qui ne fonctionne pas comme désiré.
Tu l'utilises à la ligne 457 au module 8 comme ceci:

`#install.packages("elevatr")
library(elevatr)
elv_megantic <- get_elev_raster(crop(dem_lcc, parc_megantic), proj = projection(dem_lcc), z = 13) 
` 

Mais j'obtiens un message d'erreur qui semble être lié à la projection:

![image](https://user-images.githubusercontent.com/41080954/115306148-63860c00-a135-11eb-8ed7-79f64b8474bf.png)

J'ai essayé d'autres façons de définir la projection ex: st_crs, proj4string, crs, sans succès.

De plus, c'est pas clair pour moi pourquoi le premier argument doit être le crop. Et pourquoi on ne pourrait pas simplement mettre parc_megantic. 

Aussi, est-ce nécessaire de définir proj ? dans la documentation ça dit:
A PROJ.4 string defining the projection of the locations argument. If a sp or raster object is provided, the PROJ.4 string will be taken from that. This argument is required for a data.frame of locations."
Donc que ça devrait prendre la proj directement de crop(chosebin).
Mais j'ai le même message d'erreur si je retire cet argument.

Merci!
Elise

**Comment by KevCaz** [comment]
allo @elisefilotas , 

Tu as raison, `elv_megantic <- get_elev_raster(parc_megantic, z = 13) ` suffit, pas sûr que j'ai de bonnes raisons d'avoir ajouté les autres arguments, en tout cas, rien me vient en tête. 

Pour ce qui est du problème, pas d'idée à froid. Avons-nous la même version du package?

```R
R> packageVersion("elevatr")                                                  
[1] ‘0.3.4’
```

**Comment by elisefilotas** [comment]
OK merci!
Oui, j'ai la même version du package. Je continue à investiguer ce pm.

**Comment by elisefilotas** [comment]
Je semble avoir le même problème que noté ici (où la solution est simplement de s'assurer que les packages soient à jour - ce que j'ai fait)
https://github.com/jhollist/elevatr/issues/38
Au fait, la semaine dernière, il me semble que ça marchait, et là pas.

Là, j'ai tout ré-updater mes packages et j'ai:

> version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          4                           
minor          0.3                         
year           2020                        
month          10                          
day            10                          
svn rev        79318                       
language       R                           
version.string R version 4.0.3 (2020-10-10)
nickname       Bunny-Wunnies Freak Out
`
`     
> packageVersion("elevatr")
[1] ‘0.3.5.9999’
> packageVersion("raster")
[1] ‘3.4.5’

La seule chose que je peux voir c'est que je doive ré-updater mon R puisque "raster" a été compilé avec la version 4.0.5.
Ça me gosse car c'est super long chaque fois.

**Comment by KevCaz** [comment]
est-ce que tu as essayé la solutoin avec `proj4string()`?

**Comment by KevCaz** [comment]
Auss peut etre préférable de prendre la version sur le cran ? ==> https://cran.r-project.org/web/packages/elevatr/index.html

**Comment by elisefilotas** [comment]
Je suis revenue à la version 3.0.4 et j'ai essayé avec proj4string() (ne marche pas sur un objet de classe sf tel parc_megantic) et projection(), st_crs(), crs(), etc.
Marche pas :/ 
Vraiment biz.

**Comment by KevCaz** [comment]
version 3.4.0?

**Comment by KevCaz** [comment]
meme message d'erreur?

**Comment by elisefilotas** [comment]
elv_megantic <- get_elev_raster(parc_megantic,crs(parc_megantic), z = 13)
Error in sp::CRS(prj) : 
  PROJ4 argument-value pairs must begin with +: PROJCRS["NAD83 / Quebec Lambert",
    BASEGEOGCRS["NAD83",
        DATUM["North American Datum 1983",
            ELLIPSOID["GRS 1980",6378137,298.257222101,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4269]],
    CONVERSION["Quebec Lambert Projection",
        METHOD["Lambert Conic Conformal (2SP)",
            ID["EPSG",9802]],
        PARAMETER["Latitude of false origin",44,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8821]],
        PARAMETER["Longitude of false origin",-68.5,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8822]],
        PARAMETER["Latitude of 1st standard parallel",60,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8823]],
        PARAMETER["Latitude of 2nd standard parallel",46,
            ANGLEUNIT["degree",0.0174532925199433]

**Comment by KevCaz** [comment]
et avec `st_crs(parc_megantic)$proj4string`?

**Comment by elisefilotas** [comment]
bon. désolée, ça fonctionne! même sans spécifier la projection. 
Je pensais que j'avais updater sp mais il semble que non, ce que j'ai fait et là ça marche.

**Comment by KevCaz** [comment]
good! Je clos alors!
