### ISSUE TITLE
question à propos de la fonction "aggregate"

### ISSUE THREAD

**Issue by elisefilotas** [sci1031/sci1031#59]
Allo @KevCaz,

Je suis en train compléter le module 7 sur la manipulation de données vectorielles. 
Je veux expliquer la fonction [aggregate](https://r-spatial.github.io/sf/reference/aggregate.sf.html).

Comme exemple, j'ai un shapefile qui contient des villes, leur population, et la région administrative dans laquelle chaque ville est située. 
Je veux faire un aggregate sur les régions administratives pour obtenir la population totale de chacune (la somme des populations des villes qui y sont situées).
La fonction additionne correctement. Mais on dirait qu'elle n'aggrège pas correctement la géométrie. C'est-à-dire les points qui sont associés à chaque région ne sont pas les bons points.

Pour reproduire l'exemple, il faut télécharger les données du module 7

```{r}
# importer donnees villes
villes <- st_read("Module7/data/villes/villes.shp")
villes <- villes[,"HAP_NM_TOP"]
names(villes) <- c("toponyme", "geometry")  #mettre des meilleurs noms

# importer donnees regions admini
regions <- st_read("Module7/data/regions_admin/regions_admin.shp")

# importer donnees taille de pop
pop <- read.csv("Module7/data/villes/population.csv",encoding="UTF-8")
pop <- pop[, c("munnom", "msuperf", "mpopul")] #garder juste les attributs d'intérêt

# merger pop avec villes
villes_pop <- merge(x = villes, y = pop, by.x="toponyme", by.y="munnom",  all.x = TRUE)
names(villes_pop)[2:3] <- c("superficie", "population") #mettre des meilleurs noms

# Joindre regions à villes_pop
villes_reg_pop <- st_join(villes_pop, regions[ ,"Rgns_Ad"])
villes_reg_pop

# aggreger toute les villes d'une meme region pour connaitre la pop par region
agg<-aggregate(villes_reg_pop["population"], by = list(villes_reg_pop$Rgns_Ad), FUN = sum, na.rm = TRUE)
agg
mapview(agg,zcol="Group.1")
```
Les régions sont n'importe où!
Note que j'ai essayé d'autres arguments pour la fonction aggregate (do_union = TRUE, simplify = TRUE, join = st_intersects), sans succès.

Pourtant ceci est au bon endroit
```{r}
agg_Laurentides <-subset(agg, Group.1=="Laurentides")
mapview(agg_Laurentides)
```

Si je crée moi-même un exemple simple, ça fonctionne aussi:
```{r}
# create data.frame
V <- c("a","b","c","d","e")
R <- c("region1","region1","region1","region2","region2" )
Pop <- c(15,20,25,30,7)
long <- c(-62.08,-68.83,-59.62,-73.89,-74.63)
lat <- c( 50.22,48.86,50.47,45.68,45.98)

df_pts <- cbind.data.frame(R, R, Pop, lat, long)

# create point shapefile
sh_pts <- st_as_sf(df_pts,
                   coords = c("long", "lat"),
                   crs = CRS("+proj=longlat +ellps=GRS80 +no_defs"))
mapview(sh_pts)

A<-aggregate(sh_pts["Pop"], by = list(sh_pts$R), FUN = sum, na.rm = TRUE)
A
mapview(A,zcol="Group.1")
```

Bref, je suis gossée, je ne comprends pas.
Si jamais tu as un moment pour regarder ça, ça m'aiderait. 
Sinon, on s'en reparle vendredi.

Merci!
Elise

**Comment by elisefilotas** [comment]
oups. Je viens de l'ajouter!

**Comment by KevCaz** [comment]
Donc juste un poblème de version!
